name: Allure CI

on: 
  push:
    branches: [ allure ]
 
jobs:
  end_to_end:
    name: "end to end"
    runs-on: ubuntu-latest
    steps:
     - name: "Checkout"
       uses: actions/checkout@v2

     - name: "Use Node.js 14.x"
       uses: actions/setup-node@v1
       with:
         node-version: 14.x

     - name : check pwd
       run : pwd
       
     - name : yarn install
       working-directory: ./wdio
       run: yarn install
  
     - name: "Run E2E UI tests"
       working-directory: ./wdio
       run : yarn test:wdio
       env :
          URL: 'http://https://stukstswstagingdh.azureedge.net/'
     
     - name: "Report"
       working-directory: ./wdio
       run : yarn allure generate --clean
      
    #  - name: "Report open"
    #    working-directory: ./wdio
    #    run : yarn allure serve

     - name: Test marketplace action
       uses: simple-elf/allure-report-action@master
       if: always()
       id: allure-report
       with:
         allure_results: ./wdio/allure-results
         gh_pages: gh_pages
         allure_report: ./wdio/allure-report
         allure_history: ./wdio/allure-history
     
     - name: Deploy report to Github Pages
       if: always()
       uses: peaceiris/actions-gh-pages@v2
       env:
         PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PUBLISH_BRANCH: gh-pages
         PUBLISH_DIR: ./wdio/allure-history
